export const PRIMARY_TECH_SKILLS = 'Primary Technical Skills';
export const FRESHER = 'Fresher';
export const MAX_URL_LINKS = 2;
export const MAX_AVAILABLE_SLOT = 4;
export const CANDIDATE_RESIGNED = "Resigned"
export const CANDIDATE_IMMEDIATE_JOIN = "Immediate Joining"
export const CANDIDATE_LWD = "LWD"
export const CANDIDATE_NOTICE_PERIOD = "Notice Period"
export const CANDIDATE_NEGOTIABLE_DAY = "Negotiable Days"
export const CANDIDATE_NON_NEGOTIABLE = "Non-negotiable"
export const CANDIDATE_BUYOUT = "Buyout"
export const CANDIDATE_AVAILABLE_SLOTS = "Available slots for interview"
export const CANDIDATE_JOB_CHANGE_STATUS = "Job change status"
export const CANDIDATE_JOB_ACTIVE = "Active"
export const CANDIDATE_JOB_CASUAL = "Casual"
export const CANDIDATE_JOB_PASSIVE = "Passive"
export const CANDIDATE_JOB_DORMANT = "Dormant"
export const CANDIDATE_JOB_PLACED = "Placed"
export const CANDIDATE_MAX_EXP = 30;
export const IT_BRANCHES = "1__2__3__4";
export const SECONDARY_SKILLS="Secondary Technical Skills"

